### ISSUE TITLE
Cannot import the xes log

### ISSUE THREAD

**Issue by FrankBGao** [tnolle/binet#4]
I want to load an XES file. But got nothing.
The file is BPIC12.xes
Here is the code.

from april.fs import EventLogFile
from april import Dataset

path = "C://Users//gao//Desktop//binet-master//.out//eventlogs"
path += "//new.xes"
log = EventLogFile(path)

## This one get an error
d = Dataset(log)
## And this also got an object, but nothing is in it.
d = Dataset(path)

![image](https://user-images.githubusercontent.com/20436775/67781802-31c44580-fa68-11e9-848b-410c24cbac23.png)

**Comment by tnolle** [comment]
You will first have to load the `XES` file as an `EventLog` file and transform it into the internal `JSON` format.

```python
event_log = EventLog.from_xes(xes_path)
event_log.save_json(os.path.join(EVENTLOG_DIR, 'pbic12-0.0-1.json.gz'))
```

The you can simply load the Dataset with.

```python
dataset = Dataset('bpic12-0.0-1')
```
We are saving some metadata information as part of the file name. That's why you have to use this awkward file name `bpic12-0.0-1.json.gz`. It won't work otherwise. The pattern is `<name>-<noise_value>-<id>.json.gz`.

Hope this helps.

Also, take a look at the notebooks section. This one explains the BPIC log loading.
https://github.com/tnolle/binet/blob/master/notebooks/3.A3%20BPIC%20Datasets.ipynb

**Comment by FrankBGao** [comment]
Many thanks
:)
